### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by stefan1968** [amilajack/eslint-plugin-flowtype-errors#100]
Using versions: - "eslint-plugin-flowtype": "2.37.0",
    "eslint-plugin-flowtype-errors": "3.3.2",

Getting the following errors, when I run lint:-

yarn lint v0.27.5
$ eslint ./app/**/**.js
Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at collect (/Users/stefanwalker/Projects/Influence/Frontend2/node_modules/eslint-plugin-flowtype-errors/dist/collect.js:178:3)
    at Program (/Users/stefanwalker/Projects/Influence/Frontend2/node_modules/eslint-plugin-flowtype-errors/dist/index.js:94:48)

**Comment by jdmota** [comment]
Can you provide a minimal test case with the contents of that file?

**Comment by leyyinad** [comment]
I got the same in . I didn't have the time yet to strip it down to a minimal test case, but maybe this is of help: The error happens in (list) `collect.js`, line 178.

`parsedJSONArray` is:
```js
{ flowVersion: '0.56.0',
  exit:
   { code: 110,
     reason: 'Unknown_error',
     msg: 'Unhandled exception: End_of_file' } }
```

so `parsedJSONArray.errors` and hence `parsedJSONArray.errors.filter` is not defined.

Versions are:
```
├─ babel-plugin-flow-runtime@0.11.1
├─ eslint-plugin-flowtype-errors@3.3.2
├─ eslint-plugin-flowtype@2.39.1
```

Flow finishes with no errors at all. What might cause this?

**Comment by jdmota** [comment]
Thanks! I will update my PR so that we show an error instead of ignoring.

**Comment by amilajack** [comment]
Was this resolved?

**Comment by vitbokisch** [comment]
In my case eslint seemed to be working correctly, but using this plugin broke prettier formatting and got the same error message. Not sure if this helps with debugging the error...

**Comment by jdmota** [comment]
We no longer use `filter` in the `collect.js` file. Can this be closed?

**Comment by nwoltman** [comment]
@jdmota I am very certain that this can be closed. I believe #101 did fix it and then `.filter()` was removed in #119, so this can't possibly still be a problem.
