### ISSUE TITLE
Feature request: Report flow warnings as eslint warnings

### ISSUE THREAD

**Issue by JayAndCatchFire** [amilajack/eslint-plugin-flowtype-errors#114]
This is a feature request.

Flow's linter now supports warnings as well as errors.  However, this plugin still reports warnings as errors in eslint.  Can it be adjusted to forward the correct message types to eslint?

**Comment by amilajack** [comment]
I think that would be a great idea. Unfortunately I've been really busy recently. I'd love contributions to add this :)

**Comment by amilajack** [comment]
@jdmota Do you think you can look into this?

**Comment by JayAndCatchFire** [comment]
I can give it a shot if that's okay.

**Comment by amilajack** [comment]
Of course!

**Comment by JayAndCatchFire** [comment]
I've started work on this feature this evening, but I do have a question.  Should this just be handled like this or should this be opt-in or something?

Here are the options I'm thinking of.
1. It just works as expected without any kind of modification to a user's eslint config.
2. Warnings are _ignored_ by default.  In order to opt-in, you have to add a `flowtype-errors/show-warnings` rule to your eslint config.  The advantage to this is that you could theoretically set warnings to appear as errors by setting this to `2`/`'error'`, or be ignored completely by setting it to `0`/`'off'`.  The disadvantage is that it makes this all more confusing.  I mean, if you wanted the warnings to display as errors, why wouldn't you just set the message in question to `warn` in your `.flowconfig`?

I don't have any strong personal preference.  I'd lean towards option 2 just to give users the option.  I don't presume to know or anticipate every user's bizarre workflow.  I'd really appreciate your input, @amilajack, what with it being your repo and all. :wink:

**Comment by amilajack** [comment]
Option 2 is a good idea. Also make sure to update the docs in the readme and the changelog
