### ISSUE TITLE
No matching version found for eslint-plugin-flowtype-errors@3.6.0

### ISSUE THREAD

**Issue by PavelKoroteev** [amilajack/eslint-plugin-flowtype-errors#122]
![image](https://user-images.githubusercontent.com/34572116/40709027-a648c460-63fd-11e8-96f9-478efe0e94bf.png)

**Comment by jdmota** [comment]
Do you still have this issue? Or can this be closed? Thanks

**Comment by PavelKoroteev** [comment]
Thank you for help!
