### ISSUE TITLE
Error for typeof foo === 'symbol'

### ISSUE THREAD

**Issue by Fer0x** [amilajack/eslint-plugin-flowtype-errors#133]
I have following error: ```ESLint: Cannot compare the result of `typeof` to string literal `symbol` because it is not a valid `typeof` return value. (flowtype-errors/show-errors)``` with code like this:

```js
  if (typeof value === 'symbol') {
    return value;
  }
```

**Comment by jdmota** [comment]
That is how Flow works. We can't help you with that :(

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCgG4EMA2IKAlIgN4BQiiMwimUAngA4px16EqIC8fiAcjSMAtgCM4+AaUrVqAJxRQQ8pJyIBuKogC+FHUA
