### ISSUE TITLE
Add path to `.flowconfig` to override default root path

### ISSUE THREAD

**Issue by amilajack** [amilajack/eslint-plugin-flowtype-errors#15]
Inspired by https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/8

**Comment by namjul** [comment]
We would need this feature. Is this on the roadmap?

**Comment by amilajack** [comment]
the PR for this should be pretty straightforward. Would be great if you could try your hand at it. I'm low on time this week :(

**Comment by namjul** [comment]
ok, i will have a look into it.
