### ISSUE TITLE
Allow Flow to be installed as peerDependency

### ISSUE THREAD

**Issue by amilajack** [amilajack/eslint-plugin-flowtype-errors#18]

**Comment by zperrault** [comment]
Hi @amilajack!

I'd be happy to take this on. Shouldn't be too difficult 😄 .

Is there a way you'd like to me approach this or any steps you'd like me to take when open a PR etc.?

**Comment by amilajack** [comment]
@zperrault Great! Thanks 🎉👊

**Comment by morlay** [comment]
Since the new version of flow released, if we set `[version]` in `.flowconfig`,  this plugin will be broken.

Could we publish a new version to fix it?

**Comment by amilajack** [comment]
I have no idea how the new method of versioning in flow works. I'll look into this hopefully this weekend
