### ISSUE TITLE
How to configure this with create react app without ejecting ?

### ISSUE THREAD

**Issue by iiitmanikanta** [amilajack/eslint-plugin-flowtype-errors#181]
can we configure eslint-plugin-flowtype-errors with create react app to check the flow errors in runtime?

Similar to this 
![image](https://cloud.githubusercontent.com/assets/246520/20870411/047d1f3e-ba88-11e6-98bb-06d19e919efa.gif)

This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

**Comment by nwoltman** [comment]
You'd need to use the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for that.

Are you using ESLint though? It seems like maybe the [Flow Language Support extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) is what you're really looking for.

**Comment by iiitmanikanta** [comment]
hi @nwoltman, these extensions are working fine in IDE level but I want a solution to emit errors in dev server itself so that new developers can't skip them.
we are using create react app without ejecting, so I can't extend .babelrc file

**Comment by nwoltman** [comment]
This plugin is just an ESLint plugin, so if you could run ESLint in Create React App then that's all you'd need.

Also, is there something about the [Adding Flow documentation](https://facebook.github.io/create-react-app/docs/adding-flow) in Create React App that doesn't give the functionality that you want?
