### ISSUE TITLE
Running eslint on multiple files causes flow to be run mutliple times

### ISSUE THREAD

**Issue by Adjective-Object** [amilajack/eslint-plugin-flowtype-errors#22]
in the dist source on `collect.js`, the filepath for flow to evaluate is not passed in, flow is always run with `flow --json`

This means when eslinting multiple files, flow parses the entire project. This is a huge performance cost.

**Comment by amilajack** [comment]
@Adjective-Object Yup! See https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/8#issuecomment-250958589.

**Comment by Adjective-Object** [comment]
Ah, I see that i was confused by looking at a dead codepath which had not been removed.

I am unsure what the issue you posted (on the fly linting) has to do with this issue though, would you mind clarifying? I've been working against the on-the-fly linter using SublimeLinter-eslint with no issues apart from #23.

**Comment by amilajack** [comment]
It was actually worse than this. Previously, it would run on every AST node 😆 Now it runs on every file but it only checks that file. Its MUCH faster now.

**Comment by amilajack** [comment]
Try updating to `1.2.0` to see the new changes.
