### ISSUE TITLE
plugin throws errors when flow detects no errors

### ISSUE THREAD

**Issue by Adjective-Object** [amilajack/eslint-plugin-flowtype-errors#23]
on collect.js line 114

```javascript
  return output.length
    ? filter(output)
    : true;
```

Because the stdout of collect.js is parsed by index.js, which then immediately runs it through JSON.parse, and then `filter`, which does not exist on booleans.

Suggest changing the false clause of the ternary to `[]` to correct this.

**Comment by Adjective-Object** [comment]
Alternatively, 
```javascript
return output
```

**Comment by amilajack** [comment]
Try updating to `1.3.0` and let me know if the issue persists.
