### ISSUE TITLE
A typo in a wiki page.

### ISSUE THREAD

**Issue by jyane** [amilajack/eslint-plugin-flowtype-errors#25]
Thank you for your good eslint plugin.

I found a typo in a wiki page.

https://github.com/amilajack/eslint-plugin-flowtype-errors/wiki/Getting-Started
`Create a .flowconfig with:` -> `Crate a .eslintrc with:` ?

**Comment by amilajack** [comment]
Yup! Good catch!

**Comment by amilajack** [comment]
Fixed 🎉
