### ISSUE TITLE
Use files rather than .npmignore

### ISSUE THREAD

**Issue by jfmengels** [amilajack/eslint-plugin-flowtype-errors#29]
Follows the work in #28.
When I install the plugin, I'm downloading the following:
![image](https://cloud.githubusercontent.com/assets/3869412/19300083/7731fd1a-9058-11e6-8b10-edbd12f096cb.png)
(minus the gifs when the next release occurs)

I'd recommend using the `index` field of `package.json` instead of using `.npmignore`, like [here](https://github.com/avajs/eslint-plugin-ava/blob/master/package.json#L46-L51). It's a whitelist system rather than blacklist, and it accepts specifying dirs or globs too.

By doing this, you'd be less likely to publish irrelevant files like your appveyor or eslint configurations.
Let me know if you want me to do the PR, the `files` field would probably look like
```js
{
  files: [
    "index.js",
    "dist"
  ]
}
```

You then do not have to worry about updating your .npmignore file every time you add a new file.
Let me know what you think :)

**Comment by amilajack** [comment]
Sounds great! Would be awesome if you could make a PR for this.

**Comment by amilajack** [comment]
Published as `eslint-plugin-flowtype-errors@1.4.1-alpha.0`. Would be great if you could test this out!

**Comment by jfmengels** [comment]
Looks like it's working :)

End result:
![image](https://cloud.githubusercontent.com/assets/3869412/19339196/44de8f02-9122-11e6-93b0-31aa59793070.png)
