### ISSUE TITLE
Plugin not working with Bitbucket Pipelines or TravisCI

### ISSUE THREAD

**Issue by tribou** [amilajack/eslint-plugin-flowtype-errors#41]
I'm not sure if there's anything that can be done on the side of this plugin, but I wanted to at least report that I got lots of "Required module not found" flow errors when running a private Bitbucket Pipeline CI test.  The errors were related to packages installed in `node_modules` as well as requiring other files without using a `.js` file extension (i.e. `require('../lib/routes')`).

However, the flow test would pass with no issues locally.  I was able to fix the issue by switching to using `flow-bin` directly for CI tests and using this module for only local development.

**Comment by amilajack** [comment]
Interesting. Does this happen on travis? Also can you list some general steps that I can take to reproduce this?

**Comment by tribou** [comment]
It appears to be happening in TravisCI too...

https://travis-ci.org/tribou/react-template/jobs/180236472

```
/home/travis/build/tribou/react-template/src/actions/init.js
  5:9  error  ../constants/actions:  Required module not found  flowtype-errors/show-errors

/home/travis/build/tribou/react-template/src/browser.index.js
   2:20  error  debug:  Required module not found                   flowtype-errors/show-errors
   5:27  error  react-redux:  Required module not found             flowtype-errors/show-errors
   6:41  error  react-router:  Required module not found            flowtype-errors/show-errors
   7:39  error  react-router-redux:  Required module not found      flowtype-errors/show-errors
   8:29  error  offline-plugin/runtime:  Required module not found  flowtype-errors/show-errors
   9:21  error  ./lib/react.routes:  Required module not found      flowtype-errors/show-errors
  10:29  error  ./lib/configureStore:  Required module not found    flowtype-errors/show-errors
  11:42  error  ./actions/init:  Required module not found          flowtype-errors/show-errors
```

Similar to Bitbucket, it appears to be a mix of npm packages and local files.

**Comment by amilajack** [comment]
What version of the module are you using?

**Comment by tribou** [comment]
`eslint-plugin-flowtype-errors@1.5.0`

**Comment by amilajack** [comment]
Try updating to the latest version of the plugin and let me know if that works.

**Comment by tribou** [comment]
The latest (alpha) version appears to get the same errors with version 0.36.0 of flow as well...

https://travis-ci.org/tribou/react-template/jobs/182483833

However, I'm enjoying using the latest version of flow locally! 😄

**Comment by amilajack** [comment]
Are you installing type definitions on CI?

**Comment by tribou** [comment]
Yes, I'm afraid, I went ahead and checked in `flow-typed` definitions to the git repo on the master branch which also failed here:

https://travis-ci.org/tribou/react-template/jobs/182482504

**Comment by amilajack** [comment]
@tribou can you confirm if you are still experiencing this issue issue?

**Comment by amilajack** [comment]
Closing due to no response 🙁
