### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by diegohaz** [amilajack/eslint-plugin-flowtype-errors#66]
Hi, thank you for this amazing plugin.

Could you please tell me what changed since v2? I just received notifications from Greenkeeper to update my repos, but I would like to know that before doing that.

**Comment by amilajack** [comment]
Sure thing. I'll make a PR for this. Release 3.0.0 adds support for linting errors from imported modules. Here's the issue that was fixed: https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/33. I'm certain that the new errors reported by the change will create a lot of new errors in people's linters so i bumped the major semver.

**Comment by amilajack** [comment]
https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/CHANGELOG.md

🎉

**Comment by diegohaz** [comment]
Thanks ❤️
