### ISSUE TITLE
Doesn't respect `[ignore]` in project's .flowconfig

### ISSUE THREAD

**Issue by jamsea** [amilajack/eslint-plugin-flowtype-errors#70]
Hi there, I have a .flowconfig file in the root of my project that looks something like this:

```
[include]
src

[ignore]
.*/node_modules/.*\.flow
.*/node_modules/.*/src/.*
.*/node_modules/.*/es/.*
.*/node_modules/.*/example/.*
.*/node_modules/babel-plugin-flow-runtime/.*
.*/node_modules/fbjs/.*
.*/node_modules/flow-runtime/.*
.*/foo/.*

[libs]
interfaces

[version]
>=0.40.0

[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src
unsafe.enable_getters_and_setters=true
```

When I try running `eslint` though I get all of the flow errors from files in the `.*/foo/.*` directory even though it's ignored.

My guess is the issue may have something to do with this function: https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/a90711517d2be7eb36da2cf3d9383240711daa90/src/collect.js#L78 At first glance it looks like it's looping through every single file and executing flow directly on the file. Let me know if I'm crazy.

**Comment by amilajack** [comment]
> Let me know if I'm crazy.

You're definitely not crazy! I've been experiencing this as well. The plugin only works by simply taking the errors from flow and reporting them. I feel like this is more of a flow issue -- namely which errors it returns through its api

**Comment by jamsea** [comment]
Ah that makes sense, I'm using version `0.41.0` at the moment. This might be the excuse I need to actually fix the flow errors in that folder, thanks @amilajack

**Comment by amilajack** [comment]
I would recommend reporting this error to the flowtype repo
