### ISSUE TITLE
Join efforts with eslint-plugin-flowtype 

### ISSUE THREAD

**Issue by marionebl** [amilajack/eslint-plugin-flowtype-errors#73]
I recently published `eslint-plugin-flow-check` ([link](https://github.com/marionebl/eslint-plugin-flow-check)) which basically has the same functionality as your plugin.

I am rather unhappy with crowding the eslint + flowtype naming space further but had to move quickly for a private project.

I wonder if you'd be interested in joining efforts with @gajus and me over at [gajus/eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype)? 

---
https://github.com/gajus/eslint-plugin-flowtype/issues/206

**Comment by amilajack** [comment]
@marionebl I'm actually already a collaborator of that project

**Comment by gajus** [comment]
As described in the PR I have referred you @marionebl , the two projects are distinct enough that require to exist in different namespaces. Rules that utilize flow-bin should go to `eslint-plugin-flowtype-errors`, rules that can be implemented without utilizing `flow-bin` go to `eslint-plugin-flowtype`.
