### ISSUE TITLE
enforce-min-coverage linter error 

### ISSUE THREAD

**Issue by epicallan** [amilajack/eslint-plugin-flowtype-errors#89]
I get this linter error in my file: definition for rule enforce-min-coverage was not found in flowtype-errors/enforce-min-coverage. 
I am using current plugin version 3.2.1  and eslint 3.19.0
Thanks

**Comment by amilajack** [comment]
@epicallan thanks for reporting this! I forgot to publish the new npm package after the PR to update the docs. Just pushed `3.3.0` that has this new eslint rule

**Comment by epicallan** [comment]
The update fixed it. Thanks @amilajack
