### ISSUE TITLE
Allow to disable some of the errors

### ISSUE THREAD

**Issue by WhoAteDaCake** [amilajack/eslint-plugin-flowtype-errors#93]
If [material-ui](https://github.com/callemall/material-ui/tree/v1-alpha) is used

```javascript
import { createMuiTheme } from 'material-ui/styles';
```
Error: 
> material-ui/styles. Required module not found

Will be thrown
Is there any way of going around this, instead of adding $FlowIgnore comment everywhere?

**Comment by amilajack** [comment]
You can use eslint to disable certain lines:

```js
const some: string = 12; // eslint-disable-line flowtype-errors/show-errors
```
