### ISSUE TITLE
'error Unexpected token' then combined with 'vue-eslint-parser'

### ISSUE THREAD

**Issue by igidas** [amilajack/eslint-plugin-flowtype-errors#95]
Please look at this comment:
https://github.com/mysticatea/vue-eslint-parser/issues/10#issuecomment-317260155

**Comment by amilajack** [comment]
An ESLint AST cannot be passed to `flow-bin`. Plain text can be passed to it, however. Not sure if there is a workaround for this. Will investigate.

**Comment by mysticatea** [comment]
`Program` node has the range which is program code.
I guess you can slice source code text.

```js
// src/index.js#L112
            source.text.slice(node.range[0], node.range[1]),
```

**Comment by sobolevn** [comment]
@mysticatea @amilajack do you have any progress with this issue?
Is there anything I can do to help you?

**Comment by mysticatea** [comment]
@sobolevn I'm not working on this. (I have never used flow...)
