### ISSUE TITLE
How to disable enforce-min-coverage for a file

### ISSUE THREAD

**Issue by Hypnosphi** [amilajack/eslint-plugin-flowtype-errors#96]
I have file for which I don't need to enforce minimal coverage. Unfortunately, this doesn't seem to work:
```
/* eslint-disable flowtype-errors/enforce-min-coverage */
```

**Comment by jdmota** [comment]
Have you tried

`/* eslint flowtype-errors/enforce-min-coverage: 0 */` ?

**Comment by Hypnosphi** [comment]
This one works, thanks. I guess, `eslint-disable` doesn't because it's a per-file rule?

**Comment by jdmota** [comment]
For plugins, I think you have to put quotes `"flowtype-errors/enforce-min-coverage"`

**Comment by jdmota** [comment]
I believe it has nothing to do with the rule, but instead, how eslint reads those comments.

**Comment by Hypnosphi** [comment]
> /* eslint-disable "flowtype-errors/enforce-min-coverage" */ should work too, not sure tho.

No it doesn't

**Comment by amilajack** [comment]
@Hypnosphi please add a PR with a test case. I cant reproduce this.
