### ISSUE TITLE
`flowtype-errors/show-errors` doesn't work when linting from parent directory

### ISSUE THREAD

**Issue by Hypnosphi** [amilajack/eslint-plugin-flowtype-errors#97]
Repro repo: https://github.com/Hypnosphi/flowtype-errors-nonroot
```
npm install

// outputs only no-undef error
npm lint

// outputs all the errors
npm lint-flow
```

**Comment by jdmota** [comment]
If you run `flow` directly from the parent directory, what output does it give?

**Comment by Hypnosphi** [comment]
I can't check right now, but why would I do that? I use flow only in subproject

**Comment by jdmota** [comment]
This plugin uses `flow` in the background, and uses the current working directory as root by default. If `flow` outputs nothing, I think there is nothing we can do, since we rely on it.

**Comment by jdmota** [comment]
![image](https://user-images.githubusercontent.com/18088420/29517977-762d1658-866f-11e7-9ec5-cc6741497f47.png)

The problem is that you don't have a `.flowconfig` file in the parent directory.

**Comment by jdmota** [comment]
![image](https://user-images.githubusercontent.com/18088420/29518076-e8fa641a-866f-11e7-8fdb-02d1670f8685.png)

If you add

`"settings": {
	"flowtype-errors": {
            "flowDir": "./flow"
	}
  }` to your `.eslintrc` file, it works.

This changes the root that the flow server will use.
